apiVersion: v1
kind: Pod
metadata:
  name: todoapp
spec:
  containers:
    - name: todoapp
      image: yur11lesyk/todoapp:3.0.1
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /api/readiness
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 15
        failureThreshold: 5
      livenessProbe:
        httpGet:
          path: /api/liveness
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 20
        failureThreshold: 5
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
  restartPolicy: Always
